### ISSUE TITLE
ios tweak request

### ISSUE THREAD

**Issue by iphizzle** [Lakr233/ColorfulX#10]
hello. not sure if this in the right place because this github is the only link given in the tweak description. sorry if not.  

**tweak is wonderful**. 

would like the ability to disable on lock screen. it would use even less power and also give the ability to use other lock screen tweaks, like doodle, while this tweak is active.

**Comment by Lakr233** [comment]
We regret to inform you that we do not have plans to introduce new features for the tweak. The primary reason for this decision is that we are not generating sufficient revenue, and the sales data has not met our expectations. We also have other tweaks in development that require our attention.

If you’ve purchased the tweak and have questions, please contact us directly by tapping the author’s avatar for the email button.

**Comment by Lakr233** [comment]
I'm closing this issue since it's not related to the library code. If you have any further questions or concerns, feel free to leave a comment and I'll get back to you eventually.

**Comment by iphizzle** [comment]
Thank you for the updates. They are very much appreciated!! Adding you to my donate list once my next job is complete in the coming month or months. Sent from my iPhoneOn Aug 20, 2024, at 10:51 PM, Lakr ***@***.***> wrote:﻿
I'm closing this issue since it's not related to the library code. If you have any further questions or concerns, feel free to leave a comment and I'll get back to you eventually.
