### ISSUE TITLE
创建多个 AnimatedMulticolorGradientView 后控制台会输出警告.

### ISSUE THREAD

**Issue by linhay** [Lakr233/ColorfulX#11]
SDK: 5.3.1

我在 UICollectionViewCell 用以下代码创建背景视图, 
``` swift
    private lazy var selectedBGView: AnimatedMulticolorGradientView = {
        let view = AnimatedMulticolorGradientView()
        view.setColors(ColorfulPreset.appleIntelligence.colors.map { ColorVector(ColorElement($0)) },
                       animated: false,
                       repeats: true)
        view.speed = 1
        view.bias = 0.01
        view.noise = 1
        return view
    }()
```

在滑动视图时控制台会输出以下警告.
```
CADisplayTimingsControl too many requests.
Unmatched CAFrameIntervalRange unregistration.
```
<img width="579" alt="企业微信截图_2b5a3d06-ea71-485d-8f10-08793bfae32f" src="https://github.com/user-attachments/assets/e9c142a4-7880-4bd3-a18e-a0fd71bcfdd6">

**Comment by Lakr233** [comment]
可能创建了太多的 DisplayLink。回头看一下是不是可以优化这个逻辑。看起来你的 Cell 非常多。

**Comment by linhay** [comment]
10 个左右的 Cell 就会触发, 滚动的时候也会触发
![IMG_6091](https://github.com/user-attachments/assets/5fbc5c1e-a3e7-479a-83c8-43011ac39de7)

**Comment by Lakr233** [comment]
看看新版本有没有解决问题 CADisplayLink 共享了

把 MSDisplayLink 升级到 1.1.0 看看呢

**Comment by linhay** [comment]
完美! 没有警告了
