### ISSUE TITLE
`vsync()` not called when using Auto Layout in UIKit

### ISSUE THREAD

**Issue by foyoodo** [Lakr233/ColorfulX#13]
https://github.com/Lakr233/ColorfulX/blob/8792750494245cee87eb7a50fdf4ec8cb3188a84/Sources/ColorfulX/MetalView%2BUIKit.swift#L35-L51

或许可以把 `updateQualificationCheck()` 移到 `layoutSubviews()` 里，会有其他影响吗？

**Comment by Lakr233** [comment]
可以添加一个。

我不是很理解为什么 layoutSubview 会不改变 frame。

**Comment by Lakr233** [comment]
给你加上了 看看 5.4.1 好了没 没好再开下

**Comment by foyoodo** [comment]
这么速度，可以 加上就没问题了
