### ISSUE TITLE
Report a bug: Texture Descriptor Validation MTLTextureDescriptor has a height (8520) greater than the maximum allowed size of 8192

### ISSUE THREAD

**Issue by pcccccc** [Lakr233/ColorfulX#2]
Platform:  tvOS 17.0 simulator.
 
ColorfulX Version: 2.1.3

when I used VStack to generate a rather long vertical ScrollView, and if the content is too long, it reports the error:

```Swift
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation MTLTextureDescriptor has height (8520) greater than the maximum allowed size of 8192.
```

The program breaks at line 67 in MetalView.

**Comment by Lakr233** [comment]
Could you consider relocating the 'ColorfulView' component to the background of 'ScrollView'? and check if it is still crashing. It is generally inadvisable to render a view of this size, more than 8k in your case, outside the visible area.

**Comment by pcccccc** [comment]
Yes, this works

**Comment by Lakr233** [comment]
FYI: I've added a check to get this done right.

https://github.com/Lakr233/ColorfulX/blob/main/Sources/ColorfulX/MetalView.swift#L66
