### ISSUE TITLE
App 从后台返回到前台时，deltaTime 过大导致颜色跳变

### ISSUE THREAD

**Issue by NSCruiser** [Lakr233/ColorfulX#6]
我在自己的 app 中使用 ColorfulX 时，注意到应用返回前台后颜色效果会直接「跳跃」到下一个状态。如下所示：

https://github.com/Lakr233/ColorfulX/assets/10377862/9bf8bb77-338d-436f-ad68-d00189b3a1c1

查看 ColorfulX 代码后发现，虽然应用进入后台后移除了 CADisplayLink，但是 AnimatedMulticolorGradientView 中的 lastUpdate 属性依然保留着进入后台前最后一刻的时间戳。这导致回到前台后，updateRenderParameters 中计算出的 deltaTime 较大，使得下一个渲染的颜色与进入后台前的颜色差值很大，从而产生了跳变。

目前我自己的 workaround 是在 isPaused 的 willSet 回调中（也就是应用返回前台的瞬间），强制更新一次 lastUpdate。

![Xnip2024-06-15_15-43-00](https://github.com/Lakr233/ColorfulX/assets/10377862/c96ba64a-4bd6-4f43-b9fb-e0306ed0c5bf)

不知道这里是否有更好的解决方法？谢谢！

**Comment by Lakr233** [comment]
这个我也注意到了 在 UINavigationController 做动画的时候也有这个问题 动画完成会闪烁一下 没有很好的解决方案

我在想是不是可以用 `deltaTime >= (1 / fps) * x` 作为条件来判断 这样代码更干净一点的样子

Ps: 亮色建议使用纯白色背景 + 0.1 到 0.5 左右的 Colorful 会好看一些

**Comment by NSCruiser** [comment]
感谢建议，我试一下白色背景和 0.1/0.5 的参数。

deltaTime >= (1 / fps) * x 这个判断是加载什么位置？x 是代表什么嘞？

**Comment by Lakr233** [comment]
x 是个你认为合理的参数吧 避免渲染延迟太大直接暂停渲染了 x = 1.5 ... 5 都行的样子 取决于你当前的速度 这样就保证他无论如何都不会跳

**Comment by Lakr233** [comment]
之前也在想现在的设计师不是太保守了 应该把一些方法接口弄成 open 的方便重写（就是一直感觉我自己写的框架非常 “果味”）

**Comment by NSCruiser** [comment]
我确认一下，这个修改是放在这个位置么？

![Xnip2024-06-17_22-21-30](https://github.com/Lakr233/ColorfulX/assets/10377862/b67a1727-1c59-4a34-8ef6-1f2d8193535b)

这样对于 ProMotion 屏幕会不会不太友好～

**Comment by Lakr233** [comment]
可以放这里，效果没问题就行。这个库还是比较耐操的。

至于 ProMotion，实际测试 16/30/60/120 帧在速度不大的情况下差别不大（）

**Comment by NSCruiser** [comment]
想了一下，这里应该是 guard deltaTime > 0, deltaTime <= 1 / 30 else { return } 比较合理吧～

deltaTime >= (1 / fps) * x 这个判断应该是反了，因为现在的问题是 deltaTime 太大而不是太小

**Comment by NSCruiser** [comment]
创建了个PR，你看看需不需要合入到主干上～

**Comment by Lakr233** [comment]
30.0 不能写死！！！

**Comment by NSCruiser** [comment]
那要不你看看是否公开个接口给调用方提供～或者用我之前说的那个返回前台后更新一次lastUpdate的方式？

**Comment by Lakr233** [comment]
安排上了
